name: iri
description: A Dart implementation of RFC3987 - Internationalized Resource Identifiers (IRIs)
version: 0.1.1
repository: https://github.com/dropbear-software/iri
issue_tracker: https://github.com/dropbear-software/iri/issues
topics:
  - rfc3987
  - standards
  - internationalisation
  - unicode
  - iri

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  meta: ^1.16.0
  punycoder: ">=0.2.0 <0.4.0"

dev_dependencies:
  lints: ^5.0.0
  oath: ^0.4.0
  test: ^1.24.0
